apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "my-app"
    objects: |
      - objectName: "app-password"
        secretPath: "secret/data/app"
        secretKey: "password"
