apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vault-secrets-operator-system
  name: example-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: app
  name: app-sa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: k8s-auth
  kubernetes:
    role: app-role
    serviceAccount: app-sa
    audiences:
      - vault
