apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: bob
spec:
 groups:
  - system:authenticated
 request: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RZbTlpTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBMW5VcVd5Q3IvYVorSC8vNXhCa0luOXNuSVcxcW9DZGU1RWtnNG4zQTVrL2pVVTRzCnlTN251QXFKZkdaQUU0akVnNW1MbXhidkNJMWg1OXg3cDN3TXVNSm56Yk9CaVRhMVFoWi9Selg5UzNOMktHNDAKdmRSU2FSeUhjMzl4bWJBejkwcUJFNjVxdlZBL2RYNnZIaGNUbGI2VzhTekx5YXhqT256cTNFUWJUQmRVKzBiaQprcVV3UFVSbSt1a1FlaTQyTWw4NHQ2R094S05RY2hJckhhWVdzaG5sVXpvWllFRmp5YXA3dzBsVlU2Y2VqRUpVCnVHVUpoZUt0M2VyemtoNGpHSFVPUjV3NGVFdVp0WGdMSTBVSGNQRUxjUm1uM1B3cFh4L2ROQkJOUXpqMENlbXYKRGRPbFZsd01WcmN4Sm9LeXF1TFRQalo1RCszdlFFQWlnNFJrQXdJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFNNHU4NURXRnp3WW5nUUhORnNJckZRME1lbGlqcXVoQkIyc3pBT0RlR3d3WWw0L1JaYjZ4aUZCCndsNFBPQkRIdnQ1eFp5dS9IWjRqUlJVb2s2YTgxVVJ2eXZyZjhxRkRrOVZiU1lCN0M1LzN6cUorVitkNS84Y3QKUlFaM0xnK0oveVVEUW9abDVubW1vVmU5ei9YNE5KMWc5Y0poblJVc1VNQmIrODE1TTFrMmdxenQwbmluc1RYTApsemZpeFRJTVhKa2w0bkkvOEp4Q1c3S3Y3YTIramNmbk9USzFiMC9IcWtQYkltYmNPQlQ1SzNoVkowZjd3NVM4CldkZDZMWm9vL25xVzVmUWhDRGU4bmJHK2xjb1pPWnhPRjV5bDRpQXoveVhzSEI0QXJ0dE9zakVId3loVy9CSjIKSUR1ZWE2TFZINjlzVW8zWEkyK25NN2pJK2dkbWJ6dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg=="
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 86400 # One day validity
 usages:
 - client auth
